### ISSUE TITLE
Oracle, getChangeLogLockName() return wrong handle

### ISSUE THREAD

**Issue by oey** [blagerweij/liquibase-sessionlock#16]
I have several different Liquibase changelogs, with different different `liquibaseSchemaName`  from `liquibase.properties` file. 

Using plain Liquibase without this extension, it places the Liquibase tables, including `changeloglock` in the schema specified in the property `liquibaseSchemaName`.

When using the _liquibase-sessionlock_ extension it creates the lock handle with `database.getDefaultSchemaName()`  which is the default schema for the connection.

Since we use one user for all migrations, we'd get a lot of unnecessary blocking of migrations.

My suggestion is to use `database.getLiquibaseSchemaName()` in order to get a handle that mimics the default behavior of Liquibase.

I have a fork of this repo and is currently testing this change for Oracle.

**Comment by blagerweij** [comment]
Just saw your fork, I've created a PR and merged it
