### ISSUE TITLE
Sessionlock not detected when imported as non direct dependency

### ISSUE THREAD

**Issue by staho** [blagerweij/liquibase-sessionlock#21]
Hi, I have some Kotlin services which use using Liquibase-based library (just some boilerplate) to perform the migration. I wanted to add liquibase-sessionlock to this library to introduce it to all my services with a simple library version bump. 
Unfortunately, services are using standard liquibase lock. 
I've tried to add `com.github.blagerweij.sessionlock` to MANIFEST.MF of both service and library, but without any success. 

When I added sessionlock directly to my service it started instantly. 
I'm using liquibase-core:4.15.0 and liquibase-sessionlock:1.5.3.

Do you have any idea why it doesn't work?

**Comment by blagerweij** [comment]
@staho I suspect it has something to do with classloaders: The liquibase core JAR will try to discover any service using classpath scanning. If the sessionlock JAR is not loaded in the same classloader as the liquibase-core JAR, then the result will most likely be similar to your description. If possible, please load them inside the same classloader

**Comment by StefanLobbenmeier** [comment]
@staho are you using any custom classloaders mechanisms like osgi?
