### ISSUE TITLE
CockroachDB support

### ISSUE THREAD

**Issue by Jerbell** [blagerweij/liquibase-sessionlock#32]
Hi - your library looks good & solves a bit problem with Liquibase.

CockroachDB using Postgres database drive doesn't work.  This isn't actually your fault, but Cockroach has implemented `pg_advisory_lock(key bigint)` etc but not `pg_advisory_lock(key1 int, key2 int)` (2 int version).  I've submitted:
https://github.com/cockroachdb/cockroach/issues/106575 for them to fix the issue.

At this stage let's wait for the Cockroach team to respond.

**Comment by tomholub** [comment]
Unfortunately no feedback from CRDB team so far, I think that one could take quite a while.

**Comment by blagerweij** [comment]
Hey @Jerbell , unfortunately the cockroach implementations for 'pg_advisory_lock' are just stubs that return true. See https://github.com/cockroachdb/cockroach/pull/13429/files#diff-847cf9d701af1ce1e3e44fe5b320fef17dab7880c4220b284c1f38def57bbe85R1675-R1696
So unfortunately we cannot support CockroachDB.

**Comment by Jerbell** [comment]
I did not know that.  Thanks for pointing it out @blagerweij 
BTW is there any chance you can delete PR https://github.com/blagerweij/liquibase-sessionlock/pull/35 I accidentaly created?  Thanks

**Comment by Jerbell** [comment]
Hi @blagerweij - based on this information I think it would be best if the `PGLockService.supports` method excludes CockroachDB as an option for session lock. This query will return a row if it's CRDB:
```sql
SELECT name, setting FROM pg_settings where name = 'crdb_version';
```
What do you think?
