### ISSUE TITLE
Liquibase failure due to long user-level lock name 

### ISSUE THREAD

**Issue by mdarmousa** [blagerweij/liquibase-sessionlock#41]
Hi @blagerweij,

I am running into an error with Liquibase where the generated user-level lock name is too long, resulting in this error: 

`Incorrect user-level lock name 'XXXXXXXXX........XXXXXXXXXX'`

The lock name is based on the schema name and table name, which I do not have control over changing in this case. 

Overriding the lock name calculation directly is difficult since the method that generates it is private. 

Do you have any suggestions on the best way to resolve this error without changing the schema/table names themselves? I would appreciate any guidance you can provide.

Thank you!

**Comment by mdarmousa** [comment]
Hi @blagerweij, 
I have created this tiny PR, could you have a look into it once you have a chance please
https://github.com/blagerweij/liquibase-sessionlock/pull/43
Thanks

**Comment by blagerweij** [comment]
Thanks for your contribution, there were a few issues with your code, so I decided to create a separate PR: https://github.com/blagerweij/liquibase-sessionlock/pull/44
